# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - setup
  - build
  - test

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml

print-info:
  # https://docs.gitlab.com/ee/user/project/merge_requests/merge_when_pipeline_succeeds.html
  stage: setup
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  script:
    - 'echo "Job start: $CI_JOB_STARTED_AT"'
    - 'echo "Branch: $CI_COMMIT_BRANCH"'
    - 'echo "Commit Author: $CI_COMMIT_AUTHOR"'
    - 'echo "Commit digest: $CI_COMMIT_SHORT_SHA"'

build:
  stage: build
  artifacts:
    untracked: true
  image: node:18.12-alpine3.15
  script:
    - npm ci
    - npm run lint
    - npm run format

test:
  stage: test
  dependencies:
    - build
  image: node:18.12-alpine3.15
  script:
    - npm run test
# int:
#   stage: int
#   image: node:18.12-alpine3.15
#   script:
#     - npm ci
#     - npm run lint
#     - npm run format
#     - npm publish
